### ISSUE TITLE
Great Min/Max Write-Up. A couple notes on CC Completion.

### ISSUE THREAD

**Issue by michaelochurch** [Zamiell/stardew-valley#1]
You mention wanting to unlock the Island Farm as soon as possible, and say that some items can only be attained in Winter. In fact, none of the Winter-specific items are restricted to that season. 

The Nautilus Shell is available on the Cart 1-2x per year. It's also a rare drop from a Fish Pond (though that's probably a waste of time) using crab pot catch. So, if your seed has an early Nautilus Shell, you can have your Fall Crops, and complete the Greenhouse, by Fall 10 (Hyper Speed Gro + Pumpkin). Put a few Winter Roots (available on Mines, levels 41-79) in a Seed Maker and plant your Winter Seeds in the Greenhouse on Fall 11; you can have your Crocus and Snow Yam by Fall 16. Assuming you've got all the other stuff complete (including the infamous Red Cabbage) you should be able to access Ginger Island by Fall 17. Of course, this requires tight play on everything else, but it should be doable for a min/max player.

It's interesting that you consider Stardew Predictor to be cheating. It can be abused and I'd say that most uses are cheating, but I think using it to predict the Cart (and probably only that use) is still within canonical play. My justification is that 1.5 now allows you to choose a random seed; if choosing a seed with familiar Cart behavior isn't cheating, then I don't think predicting the Cart is cheating either. Before 1.5, you weren't even guaranteed a one-year CC to be possible (ignoring the ultra-rare drop) because of the Red Cabbage.

**Comment by Zamiell** [comment]
> Hyper Speed Gro + Pumpkin

You probably mean Deluxe Speed-Gro, not Hyper. Hyper Speed-Gro it is gated behind Qi gems.

> though that's probably a waste of time

Yes, the Fish Pond method can be safely ignored.

> this requires tight play on everything else, but it should be doable for a min/max player.

You're right - checking the Traveling Cart every possible day could allow for completion of the CC in Fall 16, which would save a maximum of 13 days. I will add this information to the guide.

Of course, there are some concerns:

1) Assume that checking the Traveling Cart is a 1 hour time investment. Checking it every week would be a 2 hour time investment. Checking it every season would be a 8 hour time investment. Checking it until Fall would be a 24 hour time investment. 24 hours is equivalent to 1.2 days. We need to acknowledge that this is a huge opportunity cost, especially in Spring and Summer when every second matters.

2) We should note that this investment would only make sense if you can complete your non-island objectives for the particular run by Fall. For example, in routing a 5 Candles Challenge, this route change would probably be necessary, but in a 2-year 100% challenge, you would be maxing friendship with every villager and doing special orders, so you probably wouldn't need to invest (e.g. waste) time in getting to the Island earlier.

> I think using it to predict the Cart (and probably only that use) is still within canonical play.

As explained in the guide, we consider that cheating because you save the time that you would have to spend to run to the Traveling Cart and then run back to the farm. That essentially gives you an extra hour to do some other task which you would never normally be able to do. Since time is a resource, you can't allow things that give you free time. Furthermore, part of the strategy of the game is optimally routing the Traveling Cart run into your day, whether that be at the beginning, middle, or end of the day, depending on the tasks that you have to complete on that particular day.

> My justification is that 1.5 now allows you to choose a random seed; if choosing a seed with familiar Cart behavior isn't cheating, then I don't think predicting the Cart is cheating either. 

To be clear, in this ruleset we consider choosing a specific seed to be cheating. I would agree with you that *if* someone was using a ruleset that allows for choosing a specific seed instead of a random seed, then it would follow that they should be allowed to use Stardew Predictor. But we don't allow that.

Using a specific seed removes a lot of the strategy in the game. To put it in Poker-speak, you do not have to account the expected value of an action, and can instead do negative expected value things knowing that they will pay out. As an example, if you want to play optimally on a set seed, you must map out the specific rocks on your farm that would yield geodes using Blade's predictor, and allocate time in a day to mine only these specific rocks. That's not something you could ever do on a random seed (or without using the tool).

Some players love to do this level of optimization and planning. And I welcome you to try and play like this if you want to perform some challenge run with an extremely difficult objective that simply would not be possible using "normal" strategies. But we recommend that for most challenge runs, the game is best played without knowing what is going to come in the future, and without allowing yourself to reset the day if something goes wrong.

> Before 1.5, you weren't even guaranteed a one-year CC to be possible (ignoring the ultra-rare drop) because of the Red Cabbage.

In 1.4, players using our ruleset for one-year-CC-related-challenges are allowed to check to see if their randomly-generated seed had the possibility of Red Cabbage from the Traveling Cart. However, they **still must play the challenge like they had never done so**, meaning that from Spring 5 to the day that the seeds appear, they must check the Traveling Cart every day. Alternatively, we would allow players to just give themselves Red Cabbage Seed on Winter 14 using the console if it hasn't appeared yet in the Traveling Cart, which is essentially the same thing.

In 1.5, getting Red Cabbage Seeds from the Skull Caverns is trivial. So, players can safely ignore the Traveling Cart for all intents and purposes, regaining a huge amount of time. (Unless they are going for a Nautilus Shell, which will be contingent upon the specific kind of challenge run that they are doing.)
