### ISSUE TITLE
Min-max guide feedback... Please enable Discussions!

### ISSUE THREAD

**Issue by nathan-alden-sr** [Zamiell/stardew-valley#2]
If you enabled Discussions on this repo, folks could have a place to chat about the min-max guide without creating Issues.

Great guide, BTW! However, I am struggling with Spring 14. Finding 32,500g is no small feat. I've followed the guide to the letter and reached my fishing milestones when I should have with no backup strats. I have attempted Spring 14 three times now and have failed to come up with the required 32,500g. I chose Miner profession because the guide doesn't appear to say what level 5 mining profession to choose. Was my choice incorrect? Am I supposed to sell literally _everything_ I get after mining on Spring 14--all bars, ore, gems (except for one of the four mentioned earlier in the guide), except the ones required to craft my 21 sprinklers?

I've noticed that as the guide has gone on further, it's become less detailed in certain ways. I should've taken notes starting my playthrough so that I could share and help to improve the guide, but alas... If I can't make it past Spring 14 then I'll have to reset the entire playthrough.

I've been using a spreadsheet to perform all the calculations. Here's my spreadsheet for the beginning of Spring 14, showing that if I sold nearly everything I have, I am short 8,261g. That means I need to somehow find 8,261g on Spring 14 before saving. The fish prices are all with the 50% bonus.

![image](https://user-images.githubusercontent.com/1189759/114070402-f8ebeb00-986d-11eb-8cc6-4649c1a75a90.png)

Some things off the top of my head:

-  At one point I had to cut down extra trees in order to make an extra home chest because I was confused about what I should and shouldn't be selling. I only kept stuff necessary for Community Center bundles, along with lucky finds like Ancient Seeds.
- There were several timings that felt way too tight--"leave for home at 1:00 AM and when you get there, do stuff." I had to reset the day several times on different days due to this. My pathing is efficient, as well.
- In several places the guide is ambiguous about what you are supposed to take on your body when you move between locations or pass out in the field. For example, I was storing my copper, iron, and gold bars in my mine chest while mining on Spring 14 and had to reset because the guide didn't say to take them. The guide _is_ this specific in many places, but in some places it's not--it's inconsistent.
- My mine chest at the beginning of Spring 14 has almost two full rows of items. Was I supposed to be shuttling these home when I pass out in the days prior and putting them into my second home chest in preparation for sale? I am going to have a tough time taking everything with me to reach the 32,500g minimum.
- The guide does not appear to mention what to do with old equipment--armor and weapons. Should these be sold on Spring 14 in support of the 32,500g goal? Trashed? Stored for later?
- One big omission is mentioning the optimal crop and scarecrow placement for the beginning of spring. The reason this matters is after I harvested my kale, I still had a couple of mixed seeds growing--plants required for the Community Center. Those plants were near the scarecrow and interfered with the interlocked sprinkler design I'm required to build. It would've been nice to know to place the scarecrow centrally below the house to get maximum tillable ground coverage, and to plant the mixed seeds on the edge of the tile coverage of the scarecrow so they don't interfere with the sprinklered kale planting later on.
- The guide does not mention whether to keep the farm clear of sticks, rocks, and seeds that spawn overnight. At one point I made an executive decision to protect my initial parsnips planting with cobblestone path. Several times I had to grab the axe or pickaxe (when I had it available) and clear sticks and rocks.
- During the level 120 mining push before Spring 14, it's not clear what I'm supposed to be eating. Chub? Common mushrooms? I ended up eating a mix as I am running low on Chub.
- The guide is clear about skipping pretty much everything in the quest to reach the bottom of the mine. I understand the motivation, but that means fewer ore, gems, and other stuff to sell to reach the 32,500g goal. Isn't balance important here?

**Comment by Zamiell** [comment]
> If you enabled Discussions on this repo, folks could have a place to chat about the min-max guide without creating Issues.

I'm fine with discussion being in issues. Alternatively, you can discuss the guide on [my thread for the guide](https://forums.stardewvalley.net/threads/min-max-guide-optimal-play.4070/) on the official Stardew Valley forums.
If you didn't find the guide there, then how did you come across the guide?

> Great guide, BTW!

Thanks.

> Finding 32,500g is no small feat. I've followed the guide to the letter and reached my fishing milestones when I should have with no backup strats. I have attempted Spring 14 three times now and have failed to come up with the required 32,500g.

Are you getting a perfect catch on every fish? If you don't have 32,500g, then it isn't a big deal. Just fish all day and delay everything by a day. I wouldn't fixate on this, it isn't that important.

> I chose Miner profession because the guide doesn't appear to say what level 5 mining profession to choose. Was my choice incorrect?

Yes, that is correct, because you will eventually be getting the Blacksmith profession at level 10. I've added this now to the guide.

> Am I supposed to sell literally everything I get after mining on Spring 14--all bars, ore, gems (except for one of the four mentioned earlier in the guide), except the ones required to craft my 21 sprinklers?

Sell everything you won't need later, depending on the specific goals of your respective challenge run.
So yes, this generally includes every possible gem (except for the 4 mentioned in the guide). If you are low on money, you can consider even selling the 4 mentioned in the guide, although it will set you back later on, and gems don't really give *that* much money.
Don't ever sell metal bars (except for Iridium Bars), as thy are used for Sprinklers.

> I've noticed that as the guide has gone on further, it's become less detailed in certain ways. I should've taken notes starting my playthrough so that I could share and help to improve the guide

Sure, you can submit a pull request if you want. But in general, the guide is intended to become less detailed as time progresses, because:
1. what to do gets more and more straightforward
2. what to do will depend more and more on whatever particular challenge run you are trying to accomplish

> At one point I had to cut down extra trees in order to make an extra home chest because I was confused about what I should and shouldn't be selling. I only kept stuff necessary for Community Center bundles, along with lucky finds like Ancient Seeds.

Yep, that is pretty standard, I like to have an extra chest to keep organized as well, and it doesn't cost that much time. Little things like that probably don't belong in the guide.

> There were several timings that felt way too tight--"leave for home at 1:00 AM and when you get there, do stuff." I had to reset the day several times on different days due to this. My pathing is efficient, as well.

Can you be more specific? The "meet everyone" path is kind of specific, but other than that, the only tight part of the run is making it to the blacksmith on Spring 5. Also, remember that resetting the day is illegal in this ruleset.

> In several places the guide is ambiguous about what you are supposed to take on your body when you move between locations or pass out in the field. For example, I was storing my copper, iron, and gold bars in my mine chest while mining on Spring 14 and had to reset because the guide didn't say to take them. The guide is this specific in many places, but in some places it's not--it's inconsistent.

Can you submit a PR?

> My mine chest at the beginning of Spring 14 has almost two full rows of items. Was I supposed to be shuttling these home when I pass out in the days prior and putting them into my second home chest in preparation for sale?

Yep.

> The guide does not appear to mention what to do with old equipment--armor and weapons. Should these be sold on Spring 14 in support of the 32,500g goal? Trashed? Stored for later?

I typically destroy equipment. Alternatively, you can store it all in the mines chest, and then spend 1-2 hours making a mass-equipment sell at some point when you have enough stored. Personally, I don't think it is worth it, since the opportunity cost of 1-2 hours is going to be more than whatever you can sell stuff for.

> One big omission is mentioning the optimal crop and scarecrow placement for the beginning of spring. The reason this matters is after I harvested my kale, I still had a couple of mixed seeds growing--plants required for the Community Center. Those plants were near the scarecrow and interfered with the interlocked sprinkler design I'm required to build. It would've been nice to know to place the scarecrow centrally below the house to get maximum tillable ground coverage, and to plant the mixed seeds on the edge of the tile coverage of the scarecrow so they don't interfere with the sprinklered kale planting later on.

Oh yeah the guide can probably mention that. Can you submit a PR?

> The guide does not mention whether to keep the farm clear of sticks, rocks, and seeds that spawn overnight. At one point I made an executive decision to protect my initial parsnips planting with cobblestone path. Several times I had to grab the axe or pickaxe (when I had it available) and clear sticks and rocks.

1. Sticks, and rocks do not spawn overnight. They only spawn at the beginning of a season. There's no need to clear them unless you are creating space for more crops.
2. Seeds will spawn overnight, but only near trees and can be ignored. If the seeds are within 1-2 tiles of your crops, then destroy the tree itself so that it doesn't spawn any more seeds.
3. Weeds will spawn overnight, but only next to other weeds. Make sure weeds are not touching your crops. But don't go overboard with this, as the chance that a weed will spread is low, so if you are spending time clearing weeds that are not directly next to your crops then you are wasting your time.
4. Planting cobblestone paths is a big waste of time, don't do that.

> During the level 120 mining push before Spring 14, it's not clear what I'm supposed to be eating. Chub? Common mushrooms? I ended up eating a mix as I am running low on Chub.

Yes, eat mushrooms first, and then all of your iridium-quality Chubs. By the time you get to the Skull Caverns, you generally will still not have eaten all of your iridium-quality Chubs (unless you sold them). If you sold them, then you need to make do with whatever else is around. If you have absolutely nothing, then you need to buy Salad, which is a huge pain in the dick because the Saloon isn't open at convenient hours and you are obviously low on money in Spring.

> The guide is clear about skipping pretty much everything in the quest to reach the bottom of the mine. I understand the motivation, but that means fewer ore, gems, and other stuff to sell to reach the 32,500g goal. Isn't balance important here?

Gems don't sell for much. In terms of gold/hour, you are better off fishing. Every minute spent wandering out of your way to mine some dumb gem node is a around 150g wasted. With that said, if a gem node is close, then yes, it is best to typically mine it.

**Comment by nathan-alden-sr** [comment]
Thanks for the timely reply. I'm aware of the "no reset" rule but being a married father working a full-time job, I don't really have time to restart the entire run every time. I'm just looking for a bigger challenge than a casual playthrough. I've found this quite challenging so far!

I'll probably restart one last time and take notes for each day, then figure out what to incorporate within the guide, if I get that far.

**Comment by Zamiell** [comment]
>  I'm aware of the "no reset" rule but being a married father working a full-time job, I don't really have time to restart the entire run every time.

The idea is that you just work through mistakes and come up with alternate plans on-the-fly, which can be a fun routing exercise. What specific challenge run are you doing?

With that said, if you are still getting used to the route or still new to the game, then it might be a good idea to play one or two runs with resetting the day allowed in order to get used to things. And then later on after you are used to it, try a run where you have to do everything in 1 go. It makes it a whole lot more exciting. =)

**Comment by nathan-alden-sr** [comment]
I decided to write my own guide [here](https://github.com/nathan-alden-sr/stardew-valley) since it didn't make sense to submit PRs with the amount of changes and improvements I wanted to make.

I don't know if this is a bug or intentional programming (I suspect the latter), but branches, rocks, and Weeds absolutely can change overnight. I have screenshot evidence. One possible explanation is the game attempts to keep the path through the south of The Farm to Cindersap Forest traversable when you're upgrading tools, but this is just a speculation on my part.

I had to change my Spring 7 guide to account for this. It's happened to me in multiple games, now.

![image](https://user-images.githubusercontent.com/1189759/115146617-406c3700-a025-11eb-869f-b667afdc8e3c.png)

![image](https://user-images.githubusercontent.com/1189759/115146686-86c19600-a025-11eb-9d10-d4febb28d4bb.png)
