### ISSUE TITLE
Spring crops planting

### ISSUE THREAD

**Issue by hawstom** [Zamiell/stardew-valley#20]
Forgive my being picky. I assume you appreciate it.

1. My question about Spring 5 or 6 arises from Min-Max_Guide.md:466
"- If you do not get to Pierre's in time before he closes, **this does not change the route in any meaningful way**. Simply buy and plant the seeds tomorrow."
It's unclear to me why this would not matter since it appears you want to maximize fishing time on Spring 6 instead of detouring from the CC to the General Store. If I had got more clarity from this, I would not have put "Spring 5 or 6" in my pull request. Sorry for the confusion. I think it should be "Spring 5". And Spring 6 should probably not say "this does not change the route in any meaningful way" since as you say, it's an extra trip to the store or to the farm when you could be fishing.

2. It would be good to be precise (Cauliflower or Potato, not Bean Starter) at Min-Max_Guide.md:327 (Spring 1) that:
   - By planting additional crops beyond the 15 initial Parsnip Seeds, crows have a chance to eat one or more crops every day. However, the extra value from planting the Mixed Seeds makes this worth it. (Having random **Cauliflower or Potato** from Mixed Seeds will allow you to skip buying **them** for the Spring Crops bundle later on.)

**Comment by Zamiell** [comment]
> "this does not change the route in any meaningful way" since as you say, it's an extra trip to the store or to the farm when you could be fishing.

I would not consider a detour for seeds to be a "meaningful" difference, because you will still get to Skull Caverns around the same time.

Moreover, you are going to have to make hundreds of small adjustments like this, depending on what actual challenge run you are doing. You aren't meant to follow this guide to the T, especially if you make a mistake, because you wouldn't be allowed to reset the day, and then everything would be different from that point on. But by reading the guide you can get a general idea what your high-level goals should be.

> (Having random Cauliflower or Potato from Mixed Seeds will allow you to skip buying them for the Spring Crops bundle later on.)

submit a PR
