### ISSUE TITLE
Mushrooms in Cave

### ISSUE THREAD

**Issue by waynn** [Zamiell/stardew-valley#4]
They actually regenerate daily, not every two days just as a heads-up.

**Comment by Zamiell** [comment]
No, that isn't true.

For the purposes of this guide, you will be going to bed at 2 AM on every single night, so they will only regenerate at 12:40 PM at the earliest. At this time, you are usually doing some important task away from the farm, so it would be suboptimal to harvest them at this time. See the wiki article for mon mushrooms.

If you are doing a task at your farm at between 12:40 PM and 2 PM, feel free to harvest the mushrooms early and adjust your respective harvesting schedule for the next two days. The guide doesn't bother to mention that kind of detail because it is contingent upon too many things.

**Comment by waynn** [comment]
So I thought that too (and maybe it's different on the Switch) but I collected mushrooms three days in a row on the way to the mines. I'll screenshot it next time.

**Comment by waynn** [comment]
Ok, here are five screenshots showing -- I actually missed a day in between, and on Spring 11 the boxes are empty because I just harvested them (you can see the bottom left corner), but I figured I'd upload all of them. So maybe it's different on Switch, but I definitely harvested them 6 days in a row in the morning.

![2021050808573200-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767565-f6bada80-b1e5-11eb-87ef-8d721600a942.jpg)
![2021050814094900-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767569-f7ec0780-b1e5-11eb-8459-a1051ce756b1.jpg)
![2021050814584300-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767573-f8849e00-b1e5-11eb-85ec-4c7d9af905a3.jpg)
![2021050916104000-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767574-f91d3480-b1e5-11eb-9a87-59537124173f.jpg)
![2021051015403100-C2B49A475DF5A340494292A1BD398579](https://user-images.githubusercontent.com/318137/117767578-f9b5cb00-b1e5-11eb-8b88-b871c03c8b29.jpg)

**Comment by waynn** [comment]
@Zamiell just so you see it

**Comment by waynn** [comment]
Don't have it on PC, unfortunately. But can confirm that it's happened 10
days in a row now. Will let you know if I ever get a PC version.
